### ISSUE TITLE
res50 fcos 36.6 AP??

### ISSUE THREAD

**Issue by lzx1413** [yan-hao-tian/ConTNet#2]

**Comment by axel-li** [comment]
Thanks for your issue. We train FCOS with the original setting without tricks. The config of mmdetection is here: https://github.com/open-mmlab/mmdetection/blob/master/configs/fcos/fcos_r50_caffe_fpn_gn-head_1x_coco.py.  Then we will train FCOS with tricks, and release the new experiments.

**Comment by lzx1413** [comment]
Generally speaking, 36.6 is a very low baseline, It better to compare your method with the 38.x version.
